### ISSUE TITLE
Deadlock when plug-in is installed

### ISSUE THREAD

**Issue by CrazyCoder** [ChrisRM/material-theme-jetbrains#159] opened 2016-02-23 20:54 UTC
See https://youtrack.jetbrains.com/issue/IDEA-151397 for the thread dump.

**Comment by MatthiasWinkelmann** [comment] 2016-03-03 20:30
Duplicate of #152

**Comment by ChrisRM** [comment] 2016-07-12 10:49
Fixed in the release 0.2.0.

**Closed by ChrisRM** 2016-07-12 10:49 UTC
