### ISSUE TITLE
Every time  start IDE，setting is shown

### ISSUE THREAD

**Issue by ipuppy2** [ChrisRM/material-theme-jetbrains#949] opened 2018-09-29 14:34 UTC
<img width="1224" alt="qq20180929-222824 2x" src="https://user-images.githubusercontent.com/10703130/46246941-0e7b3100-c437-11e8-9ab0-66ad1ac8236a.png">

When i Every time  start IDE, this is shown, why? my theme ui is latest

Abount IDE:
<img width="640" alt="qq20180929-223537 2x" src="https://user-images.githubusercontent.com/10703130/46247019-138cb000-c438-11e8-9c1a-97503b889320.png">

**Comment by mallowigi** [comment] 2018-09-29 15:38
Duplicate of #936

**Closed by mallowigi** 2018-09-29 15:38 UTC
