### ISSUE TITLE
Can't set menu style in webstorm 2021.1

### ISSUE THREAD

**Issue by coolkidxu** [ChrisRM/material-theme-jetbrains#1721] opened 2021-04-09 00:19 UTC
Windows10 and macOS have the same behavior

**Comment by mallowigi** [comment] 2021-04-09 03:54
What's menu style?

**Comment by coolkidxu** [comment] 2021-04-09 04:19
![image](https://user-images.githubusercontent.com/74520733/114127836-9f4af580-992d-11eb-8042-19ece94229b7.png)
This theme cannot be applied to Menus

> What's menu style?

**Comment by mallowigi** [comment] 2021-04-09 04:26
I'm sorry, I don't understand what you're talking about. You are showing me a picture of the appearance settings.

**Comment by coolkidxu** [comment] 2021-04-09 05:32
> I'm sorry, I don't understand what you're talking about. You are showing me a picture of the appearance settings.

when I use webstorm,  I'll use plugins of Material Theme UI to setting my webstorm.
usually, it's will change the default setting for webstorm, For example, Menus line height, font size, editor background color, etc. It's work fine last two years.
but yesterday I update the newest webstorm 2020.1,  but Material Theme UI can't change Menus style.  only change Editor style success.
So I return webstorm to 2020.3, It's work fine.

**Comment by mallowigi** [comment] 2021-04-09 06:00
Which version are you on?

**Comment by mallowigi** [comment] 2021-04-09 06:09
If you hadn't followed the news, the plugin has since the beginning of the year become a paid plugin. But the compact menus feature should still be available under the free plan.

**Comment by coolkidxu** [comment] 2021-04-09 07:57
> Which version are you on?

Material Theme UI 5.6.0.1 works fine in webstorm 2020.3 and make Menus beautiful (change the default setting to Appropriate line-height and spacing)， but when I upgrade my webstorm to 2021.1,  Material Theme UI not change that default setting of Menus.

**Comment by mallowigi** [comment] 2021-04-09 08:14
Please make sure you are on 6.2.3 in 2021. You can stay on 5.7.0 if you want but you won't get new updates

**Comment by coolkidxu** [comment] 2021-04-09 08:25
> Please make sure you are on 6.2.3 in 2021. You can stay on 5.7.0 if you want but you won't get new updates

yeah, I try it, but Material Theme UI still not change the default setting to Appropriate line-height and spacing.

**Comment by mallowigi** [comment] 2021-04-09 08:30
Ok I'll take a look thanks.

**Comment by coolkidxu** [comment] 2021-04-09 09:00
> Ok I'll take a look thanks.

It's my pleasure, thanks for your support.

**Comment by linaori** [comment] 2021-05-03 08:21
I can confirm the same issues. The weird thing is that yesterday I upgraded on windows and that worked fine. My work laptop is running ubuntu and there it failed to apply the theme to the menu.

**Comment by mallowigi** [comment] 2021-05-03 08:35
Hi @linaori I still do not understand the issue. What is the menu style ?

**Comment by linaori** [comment] 2021-05-03 08:54
All the paddings and margins are gone, it just looks completely different from a few weeks ago. On my windows PC I have 6.3.3 and everything looks fine, but in 6.4.0 on my ubuntu laptop everything looks weird. Colors are not being applied either.

**Comment by linaori** [comment] 2021-05-03 09:00
This is what it looks like in 6.4.0 on my ubuntu system, and for some reason the theme also keeps resetting to Darcula instead of keeping the Material Darker Theme: 
![image](https://user-images.githubusercontent.com/1754678/116858487-bd3f0980-abfe-11eb-9c0a-6cddb861e8d2.png)

**Comment by mallowigi** [comment] 2021-05-03 09:09
And you're on the free plan, right? Let me look into it

**Comment by linaori** [comment] 2021-05-03 09:15
Correct, I've just reset my entire IDE because another plugin broke something. I will see if I can verify the theme reset issue is now fixed or if it came with 6.4.0

**Comment by mallowigi** [comment] 2021-05-03 09:39
Just opened an issue about it, looks like the theme selector in the settings is broken. In the meantime please change the theme via the Quick Switcher or the Material Theme Toolbar
https://www.material-theme.com/docs/configuration/quick-actions-panel/

**Comment by linaori** [comment] 2021-05-03 09:44
The theme switcher solution works for me. The menu is still as shown above but at least the theme is saved on restart 👍🏻

**Comment by mallowigi** [comment] 2021-05-03 09:48
I see that after the update it was resetted to 18, but you can change it here.

![image](https://user-images.githubusercontent.com/5015756/116862696-d307fb00-ac0d-11eb-8133-b1cb52e82ea1.png)

But I can see an issue with the defautl value within the free plan should be 28, not 18

**Comment by linaori** [comment] 2021-05-03 09:51
That fixed it, thanks!

**Closed** 2021-05-03 12:40 UTC
