### ISSUE TITLE
Problem with variable viewing when selecting `Variable loading policy -> On demand`

### ISSUE THREAD

**Issue by dr-costas** [ChrisRM/material-theme-jetbrains#1477] opened 2019-12-17 14:30 UTC
### Summary
Text at variable viewing (Python console or debugger console) has background which does not let you see the text, when the variable loading policy is "On demand"
...

### Expected behavior
Not to have the background at the text, so you can see the text. 
...

### Actual behavior
You have a background at the text and you cannot see the text. 
...

### Steps to reproduce (if needed)

1. First step
Pick Material darker theme. 

2. Second step
Open Python Console

3. Third step
At the settings, pick "Variables loading policy -> On demand"

4. Fourth step
Write `a = [1, 2, 3]` and you will see the background at the variables viewing window. 

![screen_shot](https://user-images.githubusercontent.com/7984120/71004365-89874080-20ea-11ea-88b4-d2952bd24c76.png)

### Environment

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here. 

No custom theme.

PyCharm 2019.3 (Community Edition)
Build #PC-193.5233.109, built on November 28, 2019
Runtime version: 11.0.4+10-b520.11 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 3.10.0-1062.7.1.el7.x86_64
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: IdeaVIM, com.chrisrm.idea.MaterialThemeUI, com.jetbrains.plugins.ini4idea, mobi.hsz.idea.gitignore, net.seesharpsoft.intellij.plugins.csv

**Comment by Eroppo** [comment] 2019-12-18 07:15
![изображение](https://user-images.githubusercontent.com/13285107/71063791-92c1ed00-217e-11ea-94a7-84c4920d2f5a.png)
Came with the same issue, a little addition: it started after updating PyCharm to 2019.3, in 2019.2 background was correct

PyCharm 2019.3 (Professional Edition)
Build #PY-193.5233.109, built on November 28, 2019
Licensed to Egorro Khm
Subscription is active until January 23, 2020
Runtime version: 11.0.4+10-b520.11 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.3.0-24-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1931M
Cores: 12
Registry: undo.documentUndoLimit=300, debugger.watches.in.variables=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: AceJump, com.arcticicestudio.nord.jetbrains, com.chrisrm.idea.MaterialThemeUI, com.tylerthrailkill.intellij.solarized, ideanginx9, izhangzhihao.rainbow.brackets, net.seesharpsoft.intellij.plugins.csv, org.logtalk, zielu.gittoolbox

**Comment by dr-costas** [comment] 2019-12-18 09:27
I checked other themes of the Material UI as well, and the same behaviour exists. That is, this problem with the non-visible text appears in most of the themes of the Material UI.

**Comment by mallowigi** [comment] 2019-12-18 10:36
Reproduced too. This looks like something new because I don't remember it happening before.

**Comment by dr-costas** [comment] 2020-01-01 17:11
Any news on that? At least some indication that somebody has taken this into account?

**Comment by mallowigi** [comment] 2020-01-01 17:34
Who is somebody? I am the sole maintainer of this project

**Comment by dr-costas** [comment] 2020-01-01 17:38
Sorry @mallowigi, but at the README file there is not mentioned something like that. I would say it is mentioned rather the opposite. That is, it is mentioned (in a implict way though) that there are many maintainers and many contributors. 

Still, this issue is about that bug at the core theme of the MaterialUI. Is there any news? Or, is there any scheduled status about it? 

Sure, it is free and stuff... I'm not asking for sale support. I'm just asking if there are any plans about the issue, so I can plan my things as well.

**Comment by mallowigi** [comment] 2020-01-01 17:46
They are contributors as they contributed at least once to the project, but aside Chris, whom had stopped contributing to the project more than two years ago, no one had done any major contributions whatsoever.

This is open source so you can expect the community to submit PRs and I will gladly accept them; but at this time I am the sole maintainer of the project.

At the moment I don’t have the time to be working on the plugin, and when I do I already have my hands full with the critical bug with the tree, so this issue will have to wait, unless you or someone tries to fix it by themselves.

**Comment by dr-costas** [comment] 2020-01-01 17:46
Great, thnx.

**Comment by mallowigi** [comment] 2020-01-02 13:51
Is it fixed now ?

**Comment by DamianVu** [comment] 2020-01-02 18:46
@mallowigi It seems fixed to me, thanks!

**Closed** 2020-01-02 18:48 UTC
