### ISSUE TITLE
The "view" button of debug panel become a shadow grey block.

### ISSUE THREAD

**Issue by A1saka** [ChrisRM/material-theme-jetbrains#1479] opened 2019-12-18 07:42 UTC
### Summary
Hello,
When I debug a long list of Python, the "view" button become a grey color block.
After uninstall Material Theme UI plugin pycharm work fine, reinstall it not work either.
Thanks for your help!

### Actual behavior
<img width="1434" alt="截屏2019-12-1811 16 28" src="https://user-images.githubusercontent.com/15502050/71065397-2231c500-21ac-11ea-845d-f9e747d69b33.png">

### Expected behavior
When click the shadow block, it turn to normal.
<img width="1438" alt="截屏2019-12-1811 16 45" src="https://user-images.githubusercontent.com/15502050/71065562-6c1aab00-21ac-11ea-93d0-79e27b24353e.png">

### Environment
PyCharm 2019.3 (Professional Edition)
Build #PY-193.5233.109, built on November 28, 2019
Licensed to Peng Chen
Subscription is active until August 13, 2020
For educational use only.
Runtime version: 11.0.4+10-b520.11 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.3
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI, izhangzhihao.rainbow.brackets, net.seesharpsoft.intellij.plugins.csv

**Comment by mallowigi** [comment] 2020-01-01 20:58
duplicate of #1477

**Closed by mallowigi** 2020-01-01 20:58 UTC
