### ISSUE TITLE
Restarting the IDE shows the wizard again 

### ISSUE THREAD

**Issue by adben** [ChrisRM/material-theme-jetbrains#934] opened 2018-09-13 18:03 UTC
After the recent update(Material Theme UI Updated to v2.9.0-pre1.) when restarting the IDE the wizard keeps showing op resetting the configuration again and again...

IntelliJ IDEA 2018.2.3 (Ultimate Edition)
Build #IU-182.4323.46, built on September 3, 2018
JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

**Comment by Clarifier** [comment] 2018-09-13 18:09
Same here.

IntelliJ IDEA 2018.2.3 (Ultimate Edition)
Build #IU-182.4323.46, built on September 3, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.18.5-200.fc28.x86_64

**Comment by lukoyanov** [comment] 2018-09-13 21:08
Please fix it.

**Comment by kirkcola** [comment] 2018-09-14 02:56
Same on Windows.

>IntelliJ IDEA 2018.2.3 (Ultimate Edition)
Build #IU-182.4323.46, built on September 4, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by hypercube1024** [comment] 2018-09-14 03:40
Same on macOS 10.13.6  
IntelliJ IDEA 2018.2.3

**Comment by sho-yamane** [comment] 2018-09-14 04:00
Please fix it.

**Comment by erikLovesMetal** [comment] 2018-09-14 06:33
Same here on macOS High Sierra Intellij IDEA 2018.2.3

**Comment by jwenting** [comment] 2018-09-14 09:29
More information about what's going on in my issue: https://github.com/ChrisRM/material-theme-jetbrains/issues/936

**Comment by mallowigi** [comment] 2018-09-14 13:02
Like I said I’m taking a break and this is a alpha version. Please revert to 2.8.3

**Comment by smutek** [comment] 2018-09-15 15:35
Merging an alpha into production, releasing it, and then taking a break seems unusual.  I manage my plugins via the IDE, the upgrade notification only tells me an update is available, it does not that mention that the update is an alpha and that the maintainer is taking a break from active development. It was only after I got frustrated that I came here to see if anyone had filed an issue.

I don't mean that to criticize you, I'm mentioning it because there's probably a lot of users experiencing the same problem who aren't going to find their way here and will just uninstall the plugin and move on. 

Reverting to 2.8.3 did the trick for me, thanks. Also and for what it's worth, in my case, the issue only impacts IntelliJ. I have not had problems with the other JetBrains IDE's I use.

**Comment by Moonpie413** [comment] 2018-09-16 04:07
Same on Manjaro Linux
IntelliJ IDEA 2018.2.3

**Comment by Trontor** [comment] 2018-09-16 08:08
I'm getting this same issue across two different computers, latest versions for both IntelliJ and Material Theme, it's really annoying.

**Comment by nvdlug** [comment] 2018-09-17 17:44
Please fix this I thought I was going crazy

**Comment by smutek** [comment] 2018-09-17 18:08
@nvdlug I downloaded it from https://plugins.jetbrains.com/plugin/8006-material-theme-ui then manually installed from disk.

**Comment by kevinwchn** [comment] 2018-09-18 03:45
Same problem here. Every time the theme will be reset and all the settings are gone. Please fix it

**Comment by mallowigi** [comment] 2018-09-18 04:41
Duplicate of #936

**Closed by mallowigi** 2018-09-18 04:41 UTC
