### ISSUE TITLE
Use different theme and color scheme

### ISSUE THREAD

**Issue by maicol07** [ChrisRM/material-theme-jetbrains#1522] opened 2020-02-21 19:13 UTC
### Summary
Plugin should allow to choose a theme (for example Material Lighter) and a different color scheme (i.e. Classic Light)

### Expected behavior
See summary above

### Actual behavior
After a PHPstorm reboot theme resets to default one (linked to the color scheme) and not the one I want

### Steps to reproduce (if needed)

1. Select a theme
2. Select a different color scheme
3. Close and reopen the IDE

### Environment

```
PhpStorm 2020.1 EAP
Build #PS-201.5616.33, built on February 20, 2020
PhpStorm EAP User
Expiration date: March 21, 2020
Runtime version: 11.0.6+8-b722.15 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1967M
Cores: 8
Registry: run.processes.with.pty=TRUE, bigger.font.in.project.view=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: Statistic, com.vladsch.idea.multimarkdown, com.almightyalpaca.intellij.plugins.discord, com.chrisrm.idea.MaterialThemeUI, com.ivanovych666.intellij.plugin.jsonsorter, com.mallowigi, de.espend.idea.php.annotation

```

Material theme options:
[material_theme.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/4237750/material_theme.zip)

**Comment by mallowigi** [comment] 2020-02-25 12:29
duplicate of another bug

**Closed by mallowigi** 2020-02-25 12:29 UTC
Labels: bug

**Comment by maicol07** [comment] 2020-02-25 12:32
@mallowigi what theme?

**Comment by mallowigi** [comment] 2020-02-25 12:36
Something with material darker at restart. I assume you were changing the theme from the setting did you not?

**Comment by maicol07** [comment] 2020-02-25 12:58
Yes, I change the theme from settings.
Also, I've found that, on reopening, without changing the theme but changing only the color scheme it resets to Material Lighter (the selected theme)

**Comment by maicol07** [comment] 2020-06-29 11:48
@mallowigi this bug reappeared with latest EAP
