### ISSUE TITLE
v6.2.3 NullPotinerException being thrown on a lot of Jetbrains 2021.1 products

### ISSUE THREAD

**Issue by GeorgeKaraszi** [ChrisRM/material-theme-jetbrains#1720] opened 2021-04-08 22:27 UTC
These errors are spamming the Event log pretty frequently.

```
Components hierarchy:

scope :contains_users ->(user_ids) { where.any...
com.intellij.ide.navigationToolbar.NavBarPanel[,0,0,1915x32,layout=java.awt.FlowLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.ui.components.JBViewport$ResourceViewBorder@4231e1d6,flags=16777219,maximumSize=,minimumSize=,preferredSize=]
com.intellij.ui.components.JBViewpo

rt[,0,1,1915x32,layout=com.intellij.ui.components.JBViewport$1,alignmentX=0.0,alignmentY=0.0,border=,flags=25165826,maximumSize=,minimumSize=,preferredSize=,isViewSizeSet=true,lastPaintPosition=java.awt.Point[x=0,y=0],scrollUnderway=false]
com.intellij.ui.components.JBScrollPane[,0,0,1920x33,layout=com.intellij.ui.components.JBScrollPane$Layout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.ide.navigationToolbar.NavBarBorder@1bda4159,flags=16777538,maximumSize=,minimumSize=,preferredSize=,columnHeader=,horizontalScrollBar=,horizontalScrollBarPolicy=HORIZONTAL_SCROLLBAR_AS_NEEDED,lowerLeft=com.intellij.ui.components.JBScrollPane$Corner[,0,33,0x0,layout=java.awt.FlowLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=],lowerRight=com.intellij.ui.components.JBScrollPane$Corner[,1915,33,0x0,layout=java.awt.FlowLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=],rowHeader=,upperLeft=com.intellij.ui.components.JBScrollPane$Corner[,0,1,0x0,layout=java.awt.FlowLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=],upperRight=com.intellij.ui.components.JBScrollPane$Corner[,1915,1,0x0,layout=java.awt.FlowLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=],verticalScrollBar=com.intellij.ui.components.JBScrollBar[,0,0,0x0,hidden,alignmentX=0.0,alignmentY=0.0,border=,flags=20971528,maximumSize=,minimumSize=,preferredSize=,blockIncrement=10,orientation=VERTICAL,unitIncrement=1],verticalScrollBarPolicy=VERTICAL_SCROLLBAR_NEVER,viewport=com.intellij.ui.components.JBViewport[,0,1,1915x32,layout=com.intellij.ui.components.JBViewport$1,alignmentX=0.0,alignmentY=0.0,border=,flags=25165826,maximumSize=,minimumSize=,preferredSize=,isViewSizeSet=true,lastPaintPosition=java.awt.Point[x=0,y=0],scrollUnderway=false],viewportBorder=]
com.intellij.ide.navigationToolbar.NavBarRootPaneExtension$3[,0,0,1920x33,layout=java.awt.BorderLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777219,maximumSize=,minimumSize=,preferredSize=]
com.intellij.ide.navigationToolbar.NavBarRootPaneExtension$1[navbar,0,36,1920x33,layout=java.awt.BorderLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=11,maximumSize=,minimumSize=,preferredSize=]
com.intellij.ui.components.JBBox[,0,0,1920x69,layout=javax.swing.BoxLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=2,maximumSize=,minimumSize=,preferredSize=]
com.intellij.ui.components.panels.NonOpaquePanel[,0,0,1920x69,layout=java.awt.BorderLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777218,maximumSize=,minimumSize=,preferredSize=]
com.intellij.ui.components.JBPanel[,0,0,1920x1567,layout=java.awt.BorderLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=11,maximumSize=,minimumSize=,preferredSize=]
com.intellij.ui.components.JBLayeredPane[null.layeredPane,0,0,1920x1567,alignmentX=0.0,alignmentY=0.0,border=,flags=2,maximumSize=,minimumSize=,preferredSize=,optimizedDrawingPossible=true]
com.intellij.openapi.wm.impl.IdeRootPane[,0,28,1920x1567,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=451,maximumSize=,minimumSize=,preferredSize=]
com.intellij.openapi.wm.impl.IdeFrameImpl[frame1,0,25,1920x1595,invalid,layout=java.awt.BorderLayout,title=another_api – notifications.rb,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=com.intellij.openapi.wm.impl.IdeRootPane[,0,28,1920x1567,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=451,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]

java.lang.NullPointerException
	at com.mallowigi.idea.ui.MTNavBarUI.doPaintNavBarItem(MTNavBarUI.java:104)
	at com.intellij.ide.navigationToolbar.NavBarItem.doPaint(NavBarItem.java:157)
	at com.intellij.ui.SimpleColoredComponent.paintComponent(SimpleColoredComponent.java:723)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1077)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JViewport.paint(JViewport.java:737)
	at com.intellij.ui.components.JBViewport.paint(JBViewport.java:237)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:590)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5270)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1654)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1629)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1566)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:262)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1333)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1063)
	at java.desktop/java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
	at java.desktop/sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:78)
	at java.desktop/sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:115)
	at java.desktop/java.awt.Container.paint(Container.java:2002)
	at java.desktop/java.awt.Window.paint(Window.java:3952)
	at com.intellij.openapi.wm.impl.IdeFrameImpl.paint(IdeFrameImpl.java:126)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:879)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:851)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:851)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:826)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:775)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1901)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

Rubymine, Datagrip, and CLion: 2021.1
OS: Mac Big Sur v11.1

This problem just started after updating from 2020.x to 2021.1 suites.
As well as the update of this plugin from v5 to the now paid for v6. 
Previous versions had no such issue.
 
[custom_style.xml.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/6281900/custom_style.xml.zip)

**Comment by kstratis** [comment] 2021-04-09 10:26
Yup. I second that! null pointer exceptions happen in Rubymine too!

<img width="1280" alt="Screenshot 2021-04-09 at 1 24 15 PM" src="https://user-images.githubusercontent.com/1859806/114166859-ed182b80-9936-11eb-81c4-e72bc5fa27cb.png">

Using macOS Catalina with the latest Rubymine 2021.1.

Please advise...

**Comment by kstratis** [comment] 2021-04-11 06:33
I managed to reproduce this:

In Rubymine it happens every time I CMD+Click on a model scope.

![Screenshot 2021-04-11 at 9 30 16 AM](https://user-images.githubusercontent.com/1859806/114294623-97639080-9aa8-11eb-8260-339a8376a307.png)

@mallowigi This appears to be an unhandled exception bug. If there's a dedicated support page for paying customers (since this is now a commercial plugin) please let me know so I can repost there.

**Comment by mallowigi** [comment] 2021-04-11 07:27
Reproduced. I'll be fixing it. 

And no, there is no support page or something, I'm still the only person on this project.

But I've always been committed to fixing issues as soon as I can, this is not changing soon :)

I'll release a fix till the end of the week.

**Comment by mallowigi** [comment] 2021-04-16 20:16
fixed

**Closed by mallowigi** 2021-04-16 20:16 UTC
Labels: bug
