### ISSUE TITLE
PHP parameter(variable) pass to a function looks a bit odd

### ISSUE THREAD

**Issue by rashidul0405** [ChrisRM/material-theme-jetbrains#138] opened 2015-12-21 09:35 UTC
Please refer to the below image:

Environment:
PHPStorm 10.0.2
JRE 1.8.0
OS X El Capitan 10.11.2

![image](https://cloud.githubusercontent.com/assets/1697082/11927631/1f2b35c6-a7f8-11e5-893e-df1f3caf6eff.png)

PHPStorm config variable:
Functions & Methods >> Parameter
![image](https://cloud.githubusercontent.com/assets/1697082/11927717/c70d959a-a7f8-11e5-9a73-c52e7caf399a.png)

**Comment by borNfreee** [comment] 2015-12-21 09:47
Duplicate of https://github.com/ChrisRM/material-theme-jetbrains/issues/133

**Closed** 2015-12-21 09:48 UTC
