### ISSUE TITLE
Edit configuration not working

### ISSUE THREAD

**Issue by Freddster** [ChrisRM/material-theme-jetbrains#440] opened 2017-09-15 08:12 UTC
✂ ---------------- ✂ ----------------- ✂ ---------------- ✂ ---------------- 
When submitting a feature or enhancement request:

1. Explain briefly what the enhancement is and why you think it would be useful.
2. Provide any other necessary or useful information regarding your issue, such as (code) examples or related links.

---

When submitting a bug report, first, read the README and check if this is a known issue.

Then, check on the Github issues if a similar issue has been posted.

If nothing of the sort, please follow the following template:
✂ ---------------- ✂ ----------------- ✂ ---------------- ✂ ---------------- 

### Summary
When entering the Edit Configurations menu to add, edit or remove for example remote debuggers, it is not possible to add a new Remote. It is also not possible to edit already configured Remotes

### Expected behavior
Add or edit Run/Debug Configurations does not allow the user to edit or add Remotes.

### Actual behavior
It should be possible to edit or add Remote configurations

### Steps to reproduce (if needed)
1. Install and use the Material UI theme
2. Go to the menu "Run" and press the "Edit Configurations..."
3. Try to add or edit a Remote

![run_debug_configuration](https://user-images.githubusercontent.com/17593039/30472636-98af2c6a-99fd-11e7-8542-057d61b3e2de.PNG)

### Environment
IntelliJ IDEA 2017.2.3
Build #IC-172.3968.16, built on August 22, 2017
JRE: 1.8.0_152-release-915-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 8.1 6.3
Plugin version: 10.4

**Comment by mallowigi** [comment] 2017-09-16 07:36
I cannot reproduce. Can you share your Material Settings and also list of plugins?

**Comment by Freddster** [comment] 2017-09-18 06:48
Here are the settings I am using for the Material UI Theme, and all the
plugins install with version number. If you want me to post this
information to the git issue, just send me a mail.

<application>
<component name="MaterialThemeConfig">
<option name="selectedTheme" value="DARKER" />
<option name="highlightColor" value="80cbc4" />
<option name="isMaterialDesign" value="false" />
<option name="accentColor" value="7cb342" />
<option name="statusBarTheme" value="false" />
<option name="tabsHeight" value="50" />
<option name="defaultBackground" value="" />
</component>
</application>


Android Support 10.2.3
Ant Support 1.0
Build JSON 1.2.1
Bytecode Viewer 0.1
CodeGlance 1.5.2
Copyright 8.1
Coverage 172.3968.16
CVS Integration 11
Eclipse Integration 3.0
EditorConfig 172.3968.16
Force Shortcuts 0.4
Git Integration 8.1
GitHub 172.3968.16
Gradle 172.3968.16
Goovy 9.0
hg4idea 10.0
l18 for Java 172.3968.16
IntelliLang 8.0
Java Bytecode Decompiler 172.3968.16
JavaFX 1.0
JSON Model Generator 0.5.0
Json2Class 1.3
JUnit 1.0
Key promoter 1.0.11
Kotlin 1.1.4
Lombok Plugin 0.15.17.2
Material Theme UI 0.10.4
Maven Integration 172.3968.16
Plugin DevKit 1.0
Properties Support 172.3968.16
Scroll From Source 1.1.3
Settings Repository 172.3968.16
Subversion Integration 1.1
Task Management 1.0
Terminal 0.1
TestNG-J 8.0
UI Designer 172.3968.16
XPathView + XSLT Support 4
XSLT-Debugger 1.4
YAML 172.3968.16

**Comment by mallowigi** [comment] 2017-09-18 17:43
Should be fixed in latest EAP

**Closed by mallowigi** 2017-09-18 17:43 UTC
