### ISSUE TITLE
Can't disable fonts from this theme

### ISSUE THREAD

**Issue by sebkaluzny** [ChrisRM/material-theme-jetbrains#881] opened 2018-08-04 12:51 UTC
Hi,
After update of PhpStorm to 18.02 (or after update of this theme), I have problem with IDE fonts. I really hate default font from theme, so I was trying to disable this by disabling "Material Fonts" from settings. But there is no difference. Override functionality seems to not work also. Didn't have that kind of problems in 18.01 (macOS 10.13)

How font look with plugin enabled:
![Enabled](https://i.imgur.com/Xp41oOG.png)

And disabled:
![Disabled](https://i.imgur.com/mDnZYUw.png)

Thanks

**Comment by mallowigi** [comment] 2018-08-04 12:56
Hi,

When you disabled the material fonts, have you restarted the ide?

**Comment by sebkaluzny** [comment] 2018-08-04 12:56
Yes multiple times

**Comment by mallowigi** [comment] 2018-08-04 19:14
The issue is fixed in 2.7.1

**Closed by mallowigi** 2018-08-04 19:14 UTC
Labels: fixed
