### ISSUE TITLE
Tabs are splitted in half

### ISSUE THREAD

**Issue by elichai** [ChrisRM/material-theme-jetbrains#1346] opened 2019-08-25 20:19 UTC
### Summary
The tabs are splitted in the middle.
...

### Expected behavior
The tabs should be fully visible
...

### Steps to reproduce (if needed)

1. Install CLion 2019.2.1
2. Install Material Theme UI 4.4.6
3. Open some project and some files and look at their tabs.

### Screenshots
![Screenshot_20190825_161359](https://user-images.githubusercontent.com/2167860/63655271-1bda9180-c754-11e9-99fc-3c38526983bf.png)

### Environment
```
CLion 2019.2.1
Build #CL-192.6262.62, built on August 21, 2019
Runtime version: 12.0.2+10 amd64
VM: OpenJDK 64-Bit Server VM by N/A
Linux 5.2.9-arch1-1-ARCH
GC: ParNew, ConcurrentMarkSweep
Memory: 1987M
Cores: 16
Registry: run.processes.with.pty=TRUE, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI

material_theme.xml:
```
<application>
  <component name="MaterialThemeConfig">
    <option name="isWizardShown" value="true" />
    <option name="userId" value="-3e8255c0:16cca6c2143:-8000" />
    <option name="version" value="4.4.6" />
  </component>
</application>
```

**Comment by mallowigi** [comment] 2019-08-25 20:29
Duplicate of #1342

Please connect to the Slack channel so we can pinpoint your issue

**Comment by goxr3plus** [comment] 2019-08-27 10:52
I have exactly the same issue :

![image](https://user-images.githubusercontent.com/20374208/63765534-e65bb280-c8d1-11e9-99a4-1cc512b1ef14.png)

**Comment by goxr3plus** [comment] 2019-08-28 08:03
@elichai  

IntelliJ IDEA 2019.2.1 (Ultimate Edition)
Build #IU-192.6262.58, built on August 20, 2019
Licensed to INTRASOFT INTERNATIONAL SA / Alexander kentros
Subscription is active until April 3, 2020
Runtime version: 12.0.1+12 amd64
VM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1967M
Cores: 8
Registry: debugger.click.disable.breakpoints=true, debugger.valueTooltipAutoShowOnSelection=true, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: IDEA Restart, Lombook Plugin, VisualVMLauncher, com.alayouni.ansiHighlight, com.dubreuia, com.github.b3er.idea.plugins.arc.browser, com.intellij.ideolog, mw.unitv, net.seesharpsoft.intellij.plugins.csv, org.jetbrains.plugins.go-template, io.snyk.snyk-intellij-plugin, com.chrisrm.idea.MaterialThemeUI, com.codota.csp.intellij, org.intellij.scala, com.intellij.kubernetes, zielu.gittoolbox


Using latest version of Material `4.6.6`

**Comment by mallowigi** [comment] 2019-08-28 09:54
Please use jdk 11

**Comment by goxr3plus** [comment] 2019-08-28 10:01
@mallowigi  It solved the issue wow , but how Java 12 affects the library after all ?

**Comment by mallowigi** [comment] 2019-08-28 10:05
Interesting question, it used to work perfectly before 2019.2.1 and somehow got broken even though the code hasn't changed. I think JB changed something in their custom JDK that inverts the tab height, but in all honesty I hate this hotfix I made since it breaks other things.

**Closed** 2019-09-10 01:48 UTC
