### ISSUE TITLE
2018.1 Git Commit Button Missing

### ISSUE THREAD

**Issue by jdeanwaite** [ChrisRM/material-theme-jetbrains#715] opened 2018-04-04 19:17 UTC
### Summary

When installing the plugin on Webstorm 2018.1 and attempting to commit code, the commit & push button is missing from the UI.

<img width="515" alt="screen shot 2018-04-04 at 12 13 49 pm" src="https://user-images.githubusercontent.com/8517615/38329166-d8c9358c-3801-11e8-9626-8333ec53d246.png">

### Expected behavior

The **Commit & Push** button should be visible.

### Actual behavior

The button is not visible.

### Steps to reproduce (if needed)

1. Install Webstorm 2018.1
2. Install Material Theme
3. Open a project with a git repository.
4. Make changes, and type cmd+k to commit.
5. Write your commit message -- then be sad because you realize the commit button is missing.

### Environment

WebStorm 2018.1
Build #WS-181.4203.535, built on March 22, 2018
Licensed to Justin Waite
Subscription is active until February 12, 2019
For educational use only.
JRE: 1.8.0_152-release-1136-b20 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.4

**Comment by matmcal** [comment] 2018-04-04 22:29
Duplicate of #714

**Closed** 2018-04-05 18:58 UTC

**Comment by jdeanwaite** [comment] 2018-04-05 18:59
Is there a schedule of releases anywhere? Would like to know when this will be available :)

**Comment by mallowigi** [comment] 2018-04-06 00:46
You can also enable material components in the settings

--
Elior
