### ISSUE TITLE
Wizard keeps starting each time I start IntelliJ

### ISSUE THREAD

**Issue by c0d3x** [ChrisRM/material-theme-jetbrains#940] opened 2018-09-20 07:01 UTC
Material Theme UI Updated v2.9.0-pre1.
Keeps starting the wizard each time I start IntelliJ and I cannot just use my last theme until I set it again. I also get the same Material UI Updated balloon saying the same message each time.

**Comment by oupvo01** [comment] 2018-09-20 07:58
I have the same problem. It's getting pretty annoying...

Material plugin version: v2.9.0-pre1
IntelliJ version: 2018.2.1

**Comment by mallowigi** [comment] 2018-09-20 08:04
Duplicate of #936

**Closed by mallowigi** 2018-09-20 08:04 UTC
