### ISSUE TITLE
Unable to save plugin settings

### ISSUE THREAD

**Issue by DarklordMogrithe** [ChrisRM/material-theme-jetbrains#441] opened 2017-09-15 21:21 UTC
### Summary

The plugin fails to save settings after modifying them (see "Actual behavior").

### Expected behavior

Plugin settings and color schemes can be modified after installation.

### Actual behavior

The default plugin settings take effect after installation, but they cannot be changed without an error. Other IDE settings can be changed before but not after failing to save the plugin settings. The following error appears when changing a setting related to the plugin.

> Unable to save plugin settings: The plugin com.chrisrm.idea.MaterialThemeUI failed to save settings and has been disabled. Please restart IntelliJ IDEA

### Steps to reproduce

1. Install the plugin.
2. Attempt to change one of the plugin's color schemes.
3. Press OK to save settings.

### Environment

* Windows 10 10.0
* IntelliJ IDEA 2017.3 EAP (Community Edition)
* Build #IC-173.2290.1, built on September 12, 2017
* Plugin versions: 0.10.4.2 (EAP), 0.10.3, and 0.8.2

**Comment by mallowigi** [comment] 2017-09-16 07:29
I cannot reproduce. Are you sure you have only one instances of the plugin?

**Comment by mallowigi** [comment] 2017-09-16 08:29
Ok i managed to reproduce. will take a look at it

**Comment by mallowigi** [comment] 2017-09-18 17:42
Should be fixed in latest EAP (0.11.1)

**Closed by mallowigi** 2017-09-18 17:42 UTC
