### ISSUE TITLE
Plugin overrides custom UI font (not editor font)

### ISSUE THREAD

**Issue by spegoraro** [ChrisRM/material-theme-jetbrains#54] opened 2015-10-12 06:50 UTC
Using this plugin breaks anything in the 'Override default fonts by' section of the appearance settings upon a restart. The selected font and size are still there and the checkbox is selected but the UI fonts are incorrect. Selecting a different font or size and applying the settings forces it to work correctly so I'm guessing the plugin is causing this somewhere during initialisation.

Tested with CLion 1.1, 1.2 EAP and Pycharm 141.2569 on Linux using GNOME 3 and OpenJDK 8u60.

**Comment by kisstkondoros** [comment] 2015-10-12 22:18
Hi,

Could you please try with https://github.com/kisstkondoros/material-theme-jetbrains/blob/fontfixlinux/Material%20Theme.zip?
I have removed some evil code :)

**Comment by groksteve** [comment] 2015-10-13 01:28
Thanks for that, unfortunately the issue is still there in all of the above environments.

**Comment by ChrisRM** [comment] 2015-10-13 08:39
I'll send out a fix for this a bit later today.

**Comment by denofevil** [comment] 2017-03-27 17:17
Fixed via #279

**Closed by denofevil** 2017-03-27 17:17 UTC
Labels: enhancement

**Comment by thebasix** [comment] 2017-04-24 14:37
Aces 👍
