### ISSUE TITLE
Blacklisted by Jetbrains

### ISSUE THREAD

**Issue by talios** [ChrisRM/material-theme-jetbrains#205] opened 2016-06-26 04:18 UTC
Thought you guys might be interested in seeing this commit:

  http://git.jetbrains.org/?p=idea/community.git;a=commitdiff;h=33c516b5fd762b5ef7d44dcb85b148435c3e4688

v0.1.9 is now listed as a blacklisted plugin. due to IDEA-157843

**Comment by talios** [comment] 2016-06-27 00:03
This is related to #196

**Comment by ChrisRM** [comment] 2016-06-27 09:44
I'll see if I can sort this out

**Comment by DarkaOnLine** [comment] 2016-06-30 05:31
+1

**Comment by jzyinq** [comment] 2016-07-05 20:15
@ChrisRM any updates on this ?

**Comment by ChrisRM** [comment] 2016-07-12 09:08
Can you guys try the newest build and let me know? Especially those experiencing an error when trying to install or during runtime.

**Comment by jzyinq** [comment] 2016-07-12 09:13
Now its working as intended. Thanks for update.

**Comment by roni-frantchi** [comment] 2016-07-12 09:27
> Can you guys try the newest build and let me know?

@ChrisRM Thanks.! Seems to work well when working with IntelliJ 2016.2 RC (162.1121.10) on OS X

**Comment by ChrisRM** [comment] 2016-07-12 09:39
Pushed it to the jetbrains plugin repo. Hoping this solves the issue. I'll keep this issue open for now.

**Comment by denofevil** [comment] 2016-07-12 10:32
@ChrisRM, I've got confirmation from @bulenkov that updated iconloader should fix deadlock

**Comment by ChrisRM** [comment] 2016-07-12 10:36
Fantastic, thanks @denofevil

**Comment by dorzki** [comment] 2016-07-12 11:32
@ChrisRM i've got the update, it got approved, i think you can close the issue!

Thanks!! :D

**Comment by Izopi4a** [comment] 2016-07-12 11:33
its seems working for me aswell

**Comment by ChrisRM** [comment] 2016-07-12 11:34
Cool, closing this 👍

**Closed by ChrisRM** 2016-07-12 11:34 UTC

**Comment by SalahAdDin** [comment] 2016-07-12 12:48
But, my PyCharm doesn't notify me about this update yet.
