### ISSUE TITLE
PHP inconsistent boolean value colours

### ISSUE THREAD

**Issue by liamkeily** [ChrisRM/material-theme-jetbrains#1643] opened 2020-09-15 11:22 UTC
### Summary

Boolean values using inconsistent colours, happening in all Material themes.

### Actual behavior

Github:

<img width="307" alt="Screenshot 2020-09-15 at 09 43 18" src="https://user-images.githubusercontent.com/2040842/93191876-f17fbb80-f73c-11ea-8f2d-1327c4a06d5c.png">

Material Dark:

<img width="379" alt="Screenshot 2020-09-15 at 09 43 05" src="https://user-images.githubusercontent.com/2040842/93191889-f5abd900-f73c-11ea-9af5-c07a6e01b1c2.png">

Atom One Light:

<img width="315" alt="Screenshot 2020-09-15 at 09 43 39" src="https://user-images.githubusercontent.com/2040842/93192154-428faf80-f73d-11ea-8642-d706dcf962a6.png">

### Expected behavior

Seems like they should all be the same colour

### Steps to reproduce (if needed)

Open the following file in PHPStorm:

```
<?php
// test.php

class Test
{
    protected $test = [
        'one'   => true,
        'two'   => false,
        'three' => false,
        'four'  => true,
        'five'  => true,
        'six'   => true,
    ];

    public function testing()
    {
        return [
            true,
            true,
            true,
            true,
            true,
            true,
            true,
        ];
    }
}

```

### Environment

PhpStorm 2020.2.1
Build #PS-202.6948.87, built on August 27, 2020
Runtime version: 11.0.8+10-b944.31 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: run.processes.with.pty=TRUE, search.everywhere.configurations=false, search.everywhere.actions=false, search.everywhere.toolwindows=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: IdeaVIM, String Manipulation, com.chrisrm.idea.MaterialThemeUI, com.vermouthx.idea, net.seesharpsoft.intellij.plugins.csv, com.wix.eslint

**Comment by mallowigi** [comment] 2020-09-15 12:16
duplicate of https://github.com/ChrisRM/material-theme-jetbrains/issues/1603

**Closed by mallowigi** 2020-09-15 12:16 UTC
