### ISSUE TITLE
Tab Hovering 

### ISSUE THREAD

**Issue by jappi00** [ChrisRM/material-theme-jetbrains#565] opened 2018-01-03 13:21 UTC
### Summary

When I hover over the Tabs then it looks weird. When I disable the Plugin then it works perfect.

![unbenannt](https://user-images.githubusercontent.com/13003175/34522088-594ed300-f091-11e7-96a6-b0b8880c4f15.PNG)

### Environment

PhpStorm 2017.3
Build #PS-173.3727.138, built on November 28, 2017
JRE: 1.8.0_152-release-1024-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by lopezs** [comment] 2018-01-03 16:29
I am experiencing the same.

For me the most recent version that doesn't have this problem is [v1.4.2](https://plugins.jetbrains.com/plugin/8006-material-theme-ui/update/41553)

### Environment

PhpStorm 2017.3.3 EAP
Build #PS-173.4301.7, built on December 27, 2017
JRE: 1.8.0_152-release-1024-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.8.0-59-generic

**Comment by mallowigi** [comment] 2018-01-03 17:28
It only happens on windows this is why I was hesitating in removing this hack.

**Comment by lopezs** [comment] 2018-01-04 01:14
It's happening for me on Linux (Xubuntu 16.04)

**Comment by jappi00** [comment] 2018-01-04 13:58
The new update didn't fix it. (1.5.2.2).

**Comment by mallowigi** [comment] 2018-01-07 08:32
duplicate of #548

**Closed by mallowigi** 2018-01-07 08:32 UTC
