### ISSUE TITLE
Restart Popup resets the color scheme

### ISSUE THREAD

**Issue by andrzejsliwa** [ChrisRM/material-theme-jetbrains#807] opened 2018-06-10 18:25 UTC
### Summary

Editor Color Scheme is reverting to default. I have my own Copy of Dark Material which is customized (not standard one) 

### Expected behavior

Material Theme should respect user color scheme
<img width="1938" alt="screen shot 2018-06-10 at 20 25 55" src="https://user-images.githubusercontent.com/9280/41205004-908413ee-6cec-11e8-8785-09796e77a6a6.png">

### Actual behavior

Material Theme after update today is falling back to Default theme (without respecting user settings stored in `Settings Repository` or `IDE Settings`)
<img width="1938" alt="screen shot 2018-06-10 at 20 20 07" src="https://user-images.githubusercontent.com/9280/41204952-c1780e98-6ceb-11e8-9ce9-08271c4bbf8a.png">

...

### Steps to reproduce (if needed)

Update plugin to recent version

You can also add Screenshots for a better understanding.

### Environment
<img width="994" alt="screen shot 2018-06-10 at 20 19 54" src="https://user-images.githubusercontent.com/9280/41204950-be8b3232-6ceb-11e8-85f7-5c38303ac5cc.png">

<img width="596" alt="screen shot 2018-06-10 at 20 40 37" src="https://user-images.githubusercontent.com/9280/41205175-9a741082-6cee-11e8-91da-e46ed789cbdc.png">

The main difference between build in Darker theme and my is few customizations likes:

<img width="411" alt="screen shot 2018-06-10 at 19 59 08" src="https://user-images.githubusercontent.com/9280/41205085-5cdbe39a-6ced-11e8-8271-57ca3acc66da.png">

About providing my settings.jar, I'm not sure how secure it is to share over github publicly

here is my customized Darker theme:

[Material Theme - Darker.icls.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/2088135/Material.Theme.-.Darker.icls.zip)

BTW: Would be great to always introduce new settings with flag switched to off, for example after upgrade my Project View tree was set to 12 pixel font. If you want to recommend new feature please use release logs, not by turning it ON by default

**Comment by mallowigi** [comment] 2018-06-10 20:30
For the tree size font: I’ve experienced this as well, therefore a setting has been introduced in 2.4.0.3

As for the rest I’ve also experienced this behavior, but so far i don’t know why it is happening, investigating

**Comment by mallowigi** [comment] 2018-06-11 06:32
Ok I tried to reproduce it but to no success. 

GoLand 2018.1.4
Build #GO-181.5087.39, built on May 24, 2018
Licensed to Material Theme Jetbrains / Elior Boukhobza
Subscription is active until October 17, 2018
For non-commercial open source development only.
JRE: 1.8.0_152-release-1136-b39 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

I use the version 2.4.0.3-2018.1 of the plugin

Can you provide more information about when is this happening?

**Comment by andrzejsliwa** [comment] 2018-06-11 07:17
This happen, everytime I change something related to Material Design, for example after I changed icons settings again Goland switched back to Default Theme. This looks like some issue between build in "IDE Settings Sync" and Material Theme.

**Comment by mallowigi** [comment] 2018-06-11 11:17
I tried many combinations but I can't reproduce... You're not using the EAP aren't you?

**Comment by andrzejsliwa** [comment] 2018-06-11 12:48
<img width="1880" alt="screen shot 2018-06-11 at 14 47 31" src="https://user-images.githubusercontent.com/9280/41232375-746285c0-6d86-11e8-8e89-453f255aada6.png">

After updating material design plugin on RubyMine have same problem

**Comment by andrzejsliwa** [comment] 2018-06-11 12:49
@mallowigi  lets talk on skype, I can share my screen and help you reproduce it

**Comment by andrzejsliwa** [comment] 2018-06-11 13:10
After changing font size in `Appearance -> Override defaults font by...`, also colored material icons going back (even if I have selected Monohromatic in settings of material). After restart icons are mono again.

**Comment by mallowigi** [comment] 2018-06-11 13:38
Talk to me via the Gitter channel

**Comment by mallowigi** [comment] 2018-06-11 15:25
Ok so it happens because of the restart popup. Closing the popup and restarting manually does not trigger the issue.

**Comment by mallowigi** [comment] 2018-06-11 19:23
Closing this. Looks like an IDE issue, I cannot change what is the restart popup doing, and from the look of things it doesn't seem to happen on 2018.2 EAP. Looks like a regression bug, not related to the plugin.

If you need to restart just restart manually.

**Closed by mallowigi** 2018-06-11 19:23 UTC
