### ISSUE TITLE
Override Accent Color from Theme checkbox does not work

### ISSUE THREAD

**Issue by dcorbe** [ChrisRM/material-theme-jetbrains#1550] opened 2020-04-11 10:31 UTC
Platform: Mac OS X
Material Version: 5.1.0
IDE Version: IntelliJ IDEA Ultimate 2020.1

The checkbox to Override Accent Color from Theme just does not work.  I prefer the theme-provided accent color for editor tabs, but I have to manually pick the color in the Material appearance settings.

**Comment by mallowigi** [comment] 2020-04-11 17:04
Sorry, can't reproduce.

**Comment by dcorbe** [comment] 2020-04-11 20:35
@mallowigi 

After some more investigation, I figured out that the "Accent Color" setting in Material UI is completely overriding my theme's settings for certain UI elements.   Chiefly, EditorColors.TAB_UNDERLINE.

How do I override the accent color in the Material UI theme without having to pull it in as a dependency to my theme?

**Comment by mallowigi** [comment] 2020-04-11 20:52
The plugin is using a different implementation for the tabs, allowing for instance the different tab highlight settings. In any case, you can override the accent color for the tabs only by setting the “Tab Indicator Color” in the tab settings. This won’t be using the color scheme color but I think you could live with that, without the global accent color affecting it.

**Comment by dcorbe** [comment] 2020-04-12 23:22
That's fine for me, but I'm working on a theme for distribution and I don't want to have to pull Material in as a dependency.  

Is there any way Material can derive the accent color setting in unsupported themes?  using TAB_UNDERLINE to derive the accent color seems like a way to play nice with other themes without compromising the core of Material UI.

**Comment by mallowigi** [comment] 2020-04-13 04:40
What do you mean? To get the accent color from the tab_underline color or the opposite?

Keep in mind that the accent color affects all UI components so getting this value from the content of a setting affecting only tab elements seems overkill. 

On the other hand, if what bothers you is only that the tab underline is overwritten by the plugin, I can add a line to take the tab underline color from the color scheme settings before pulling from the accent/tab underline color.

Wdyt ?

**Comment by dcorbe** [comment] 2020-04-13 15:03
I'm suggesting that you get the accent color for 3rd party themes from somewhere.   Whether that's from TAB_UNDERLINE or another value, is up to you.  

> On the other hand, if what bothers you is only that the tab underline is overwritten by the plugin, I can add a line to take the tab underline color from the color scheme settings before pulling from the accent/tab underline color.

This seems like a reasonable compromise, but there may be issues with other third party themes in the future.  This is merely a suggestion as to how you might be able to play nice with other content creators.

**Comment by mallowigi** [comment] 2020-04-13 15:27
Again, the accent color is a feature available to the Material Theme only. There's no such option in any of the third party themes, so there's no way I can take it from them. Unless there is a specific property in theme metadata or color schemes referring to such a thing, I can't magically guess what accent color to display.

Just to remind you: up to version 5.0, there was no support for third party themes within the Material Theme plugin. Using third party themes would mean disabling the plugin completely. Now from version 5.0 there is **partial support**, e.g. the plugin can load third party themes but since they are different implementations, it does its best to figure out how to convert native themes to material themes. For instance, as I said before, accent colors are not available in native themes, so the plugin is taking another property, such as Caret Color or Tab Underline to define the accent color. It wouldn't work perfectly but for the list of themes I've tested with, it does a pretty good job at it.

That being said, I think you're actually referring to **3rd party color schemes**, as `TAB_UNDERLINE` is a color scheme property, not a theme property. In this specific case, you're actually right as the Tab Underline color should be taken from different sources, in the following order:

1. If the "Tab Highlight color" feature is enabled, use this color.
2. Otherwise, check if there is a TAB_UNDERLINE property in the current color scheme.
3. Finally, use the accent color.

This is how I'm going to implement it as it makes more sense.

**Comment by mallowigi** [comment] 2020-04-14 12:25
fixed in 5.2

**Closed by mallowigi** 2020-04-14 12:25 UTC
Labels: 5.2
