### ISSUE TITLE
Material theme 2.9.0 pre1 loses settings

### ISSUE THREAD

**Issue by mrgrieves4** [ChrisRM/material-theme-jetbrains#952] opened 2018-10-01 11:00 UTC
I'm using IntelliJ Ultimate on Windows 10 via Jetbrains Toolbox app, and I've not really used it much since I've installed Mateiral.  I updated to the latest version of the plugin and now every time I startup I lose my settings.

* On startup the wizard always shows, and I have to dismiss it
* The colour scheme resets to one of the defaults, and I have to reselect my custom dark theme.  Fortunately my theme is retained, but all other settings seems to revert to default (e.g. tab spacing, compact sidebar, theme indicator, contrast mode etc.)
* When I change to compact sidebar, the menu font goes very small.  (I have overridden the default font size in intellij to make it bigger).  But when I disable the theme indicator in the status bar it goes back to normal.

I've not really used intellij much (I use PyCharm, Rider and WebStorm mostly).  I haven't tried updating the plugin in the others so I can't be sure that the problem is this version or if it's something to do with intellij ultimate.  (It's 2018.2.4)

The plugin tells me it's a pre-release, but I can't see how I'm supposed to roll it back to the previous version as I don't get an option to do that.  I'm also getting nagged about it every time I start the other IDEs.  I think it would be much better to not release something until it's actually finished.

I do love this plugin though as it makes intellij usable for me.

**Comment by mallowigi** [comment] 2018-10-01 11:11
Duplicate of #936

**Closed by mallowigi** 2018-10-01 11:11 UTC
