### ISSUE TITLE
IDE changed back to previous theme after restart

### ISSUE THREAD

**Issue by Shay-repos** [ChrisRM/material-theme-jetbrains#1743] opened 2021-05-03 16:48 UTC
### Summary
After changing theme and restarting IDE, old theme is still used
App still keeps other settings
I'm using paid version of plugin
Reinstall plugin does not help

### Expected behavior
New theme is used

### Actual behavior
Theme is reset to old one

### Environment

PyCharm 2021.1.1 (Professional Edition)
Build #PY-211.7142.13, built on April 21, 2021
Runtime version: 11.0.10+9-b1341.41 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1526M
Cores: 12
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: com.mallowigi (36.0), com.chrisrm.idea.MaterialThemeUI (6.4.0.1)

**Comment by mallowigi** [comment] 2021-05-03 18:23
duplicate of https://github.com/ChrisRM/material-theme-jetbrains/issues/1739

In the meanwhile, please change themes via the Quick Actions Panel.

**Closed** 2021-05-06 20:13 UTC
