### ISSUE TITLE
When you open explorer, it is always black

### ISSUE THREAD

**Issue by wuyouxin** [ChrisRM/material-theme-jetbrains#1434] opened 2019-11-15 12:24 UTC
Mac os Version 10.13.6
## The material temem UI version is shown in the figure
![image](https://user-images.githubusercontent.com/22029449/68942943-c9ee5880-07e4-11ea-9281-f60636ac3ced.png)

## When I open explorer, it is always black, as shown in the figure, I have reinstalled it many times, and so on

![image](https://user-images.githubusercontent.com/22029449/68943005-f5714300-07e4-11ea-9a84-f515d002fead.png)

**Comment by mallowigi** [comment] 2019-11-15 12:33
Explorer is not part of the IDE but part of MacOS.

**Comment by wuyouxin** [comment] 2019-11-15 12:40
Other software opens the resource manager in white. When you install the material temem UI, it turns black

**Comment by mallowigi** [comment] 2019-11-15 21:42
Have you tried with the plugin disabled?

--
Elior

**Comment by wuyouxin** [comment] 2019-11-19 15:20
Disable the plug-in, switch the white theme, it becomes normal, cut it into Dacula, it becomes black

**Comment by mallowigi** [comment] 2019-11-19 15:51
even on the light themes ?

**Comment by wuyouxin** [comment] 2019-11-21 06:13
Light Themes it's normal

**Comment by mallowigi** [comment] 2019-11-21 07:10
There you have it.

**Comment by wuyouxin** [comment] 2019-11-21 07:28
I mean, it's normal to disable the material temem UI and use the default light themes of the system

With the light themes of the material temem UI, it is also black

**Comment by wuyouxin** [comment] 2019-12-02 03:26
My other computer has this theme installed. This is also the case. When opening a new project, explorer is black. Delete the theme and replace it with the default white theme. Explorer is normal

**Comment by Denis-Golyakov** [comment] 2019-12-02 11:34
It's even worse for me :D

![image](https://user-images.githubusercontent.com/36266499/69956387-809e4880-1508-11ea-8afb-a133799b7b09.png)

**Comment by mallowigi** [comment] 2019-12-02 12:01
Can you tell me what JDK you are using ?

**Comment by wuyouxin** [comment] 2019-12-03 06:30
WudeiMac:~ wu$ java -version
java version "1.8.0_192"
Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)

**Comment by wuyouxin** [comment] 2019-12-03 06:34
I use the theme of lighter theme. Explorer is white. When I switch to the black theme of ocean theme, explorer turns black

**Comment by mallowigi** [comment] 2019-12-03 19:30
I can't reproduce this. Maybe it's something on High Sierra, but I only have Mojave and Catalina at the moment.

**Comment by mallowigi** [comment] 2019-12-05 07:09
I checked in high sierra, and my explorer is dark even though there is no dark mode in high Sierra, and the explorer window is light inside.

In short it looks like an issue with 2019.3 and High Sierra. There is no way to fix this.

Please update to Catalina.

**Closed** 2019-12-05 07:09 UTC

**Comment by wuyouxin** [comment] 2019-12-05 07:47
Thank you

**Comment by nmfzone** [comment] 2019-12-28 01:02
+1 since it's happened to me on High Sierra. Yes, maybe it's only happened on High Sierra. It's very annoying for me..

I hope this can be fixed 🙏

**Comment by mallowigi** [comment] 2019-12-29 11:00
No I can’t fix it.

**Comment by wuyouxin** [comment] 2019-12-29 11:04
I've tried. Under high Sierra, it's good not to install material theme. The default dark of idea is good. As long as material theme is installed, there will be problems
