### ISSUE TITLE
Red background on each checkboxes

### ISSUE THREAD

**Issue by lbenard** [ChrisRM/material-theme-jetbrains#943] opened 2018-09-23 00:30 UTC
### Summary
Strange red background below checkboxes

### Expected behavior
The checkboxes should have the same background as everything else

### Actual behavior
This red background appears for every default theme I tried
![2018-09-23-020247_728x399_scrot](https://user-images.githubusercontent.com/41705066/45922774-8eecdf80-bed5-11e8-933e-c27f16ee6e73.png)
![2018-09-23-020846_1059x737_scrot](https://user-images.githubusercontent.com/41705066/45922776-9e6c2880-bed5-11e8-96ea-b3191a137a7a.png)

### Steps to reproduce (if needed)
This is a new IntelliJ installation, no other plugin is actually installed. I even tried reinstalling everything.

### Environment
IntelliJ IDEA 2018.2.4 (Ultimate Edition)
Build #IU-182.4505.22, built on September 18, 2018
JRE: 1.8.0_172-b11 amd64
JVM: OpenJDK 64-Bit Server VM by Oracle Corporation
Linux 4.17.11-arch1
Tried versions: 2.9.0-pre1, 2.8.3

material_theme.xml:
```<application>
  <component name="MaterialThemeConfig">
    <option name="version" value="2.8.3" />
    <option name="selectedTheme" value="MONOKAI" />
    <option name="isCompactStatusBar" value="true" />
    <option name="isCompactTables" value="true" />
    <option name="darkTitleBar" value="true" />
    <option name="compactDropdowns" value="true" />
    <option name="userId" value="-733ac91d:16603cd225f:-8000" />
    <option name="isHighContrast" value="true" />
    <option name="isWizardShown" value="true" />
  </component>
</application>

**Comment by mallowigi** [comment] 2018-10-01 18:58
I am not able to reproduce and there is nothing in the code related to this. Can you try on a clean install?

**Comment by DrGlitchMX** [comment] 2018-10-18 19:04
I do experience the exact same behavior on my JetBrains products (WebStorm, IntelliJ IDEA, PHPStorm). If you come up with any suggestion on how to tackle this, I would be glad to provide assistance.

I am seeing this on one of my machines only. Both machines run Debian + KDE. I experience this bug on the machine running Debian testing, the other one runs stable.

**Comment by lbenard** [comment] 2018-10-18 23:02
> I am not able to reproduce and there is nothing in the code related to this. Can you try on a clean install?

Sorry for being late to reply, but I already mentioned it was a totally clean install

> I do experience the exact same behavior on my JetBrains products (WebStorm, IntelliJ IDEA, PHPStorm). If you come up with any suggestion on how to tackle this, I would be glad to provide assistance.
> 
> I am seeing this on one of my machines only. Both machines run Debian + KDE. I experience this bug on the machine running Debian testing, the other one runs stable.

On my case, it was Arch + i3, everything up to date.

**Comment by mallowigi** [comment] 2018-10-19 06:08
So it’s a Linux issue? Ok I’ll try to reproduce with a vm.

**Comment by DrGlitchMX** [comment] 2018-10-19 06:30
It quite probably is. It seems like it has sth. to do with the "Material Components" - switching them off and falling back to the default does not show the issue.

**Comment by mallowigi** [comment] 2018-10-19 17:42
It will take too much time and energy to install an arch vm and to configure it... Maybe if you might connect to slack one day we can try to debug live, but until then I can't do much.

**Comment by lbenard** [comment] 2018-10-22 11:58
I just tried again on Anarchy Linux (which is basically Arch) with the exact same IntelliJ IDEA build, and it works perfectly.
> I am seeing this on one of my machines only. Both machines run Debian + KDE. I experience this bug on the machine running Debian testing, the other one runs stable.
Maybe it has something to do with the kernel. Right now I'm using 4.14.76-1 LTS.

**Comment by mallowigi** [comment] 2018-10-22 17:50
Good grief. I don't want to keep issues that are hard to reproduce and there is nothing in the code that could trigger that. Closing for the moment. If it happens again tell me.

**Closed by mallowigi** 2018-10-22 17:50 UTC

**Comment by DrGlitchMX** [comment] 2018-12-04 19:36
As of 2018-12-04, this is no longer an issue on my Debian/testing machine.
I am perfectly confident to deem this an issue **not** related to the material theme, yet more probably to some widget renderer.
I am not really familiar with the renderer-setup employed by the JetBrains IDEs and the Material-UI, but I am confident this rendering issue of does not find its root-cause within the Material-Theme.

Sorry for bothering you, @mallowigi with this - I think you are doing a great job and provide excellent response times. Please keep up the good work because I really do enjoy the results!

**Comment by r0b1n1sl4m** [comment] 2019-07-06 17:56
Same issue in Deepin 15 :(
