### ISSUE TITLE
Update prompt has dark text on dark background

### ISSUE THREAD

**Issue by SkylerLS** [ChrisRM/material-theme-jetbrains#974] opened 2018-10-12 16:53 UTC
### Summary

The update prompt when PhpStorm has a new version out has some dark text on an already dark background. Some of the text is light and readable though.

### Expected behavior

You can read light text on a dark background

### Actual behavior

You can't read dark text on a dark background

### Steps to reproduce (if needed)

1. Wait until PhpStorm has a new version
2. Open the update prompt

See:
![screen shot 2018-10-12 at 12 43 17 pm](https://user-images.githubusercontent.com/21369525/46882461-cdaeef00-ce1c-11e8-92ba-e074bd2f30d9.png)

### Environment

PhpStorm 2018.2.5
Build #PS-182.4892.16, built on October 11, 2018
Licensed to LightSpeed Retail Inc. / Skyler Wittman
Subscription is active until February 17, 2019
JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

Material theme version 2.9.3.1

**Comment by mallowigi** [comment] 2018-10-13 10:55
Can't reproduce http://prntscr.com/l5lkzt

It's also hard to mimic since it's not possible to download older versions that would trigger the update. 

I don't know why you have this but I am closing it since it's too much time consuming.

If others have this problem then I'll check

**Closed by mallowigi** 2018-10-13 10:55 UTC
