### ISSUE TITLE
Export my Material Theme settings.

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [ChrisRM/material-theme-jetbrains#868] opened 2018-07-30 12:00 UTC
Is there a way to only import/export the Material Theme settings?. If not, it should be a great feature so we can share themes easily.

**Comment by mallowigi** [comment] 2018-07-30 12:12
You can already find your configuration inside your settings folder, but yeah a button like for the color schemes can be a nice idea

**Comment by bsavio** [comment] 2018-07-31 17:46
Are you talking about this?

<application>
  <component name="MaterialThemeConfig">
    <option name="version" value="2.7.0" />
    <option name="highlightColor" value="80cbc4" />
    <option name="accentColor" value="80cbc4" />
    <option name="userId" value="1453d0bc:1645b4c9793:-7fff" />
    <option name="allowDataCollection" value="true" />
  </component>
</application>

**Comment by zoechi** [comment] 2018-09-24 13:01
What is the "settings folder" on Mac?
This is the 2nd time that I lost the Material Theme setting when I updated IntelliJ and plugins.
How can I avoid that?

**Comment by arnesacnussem** [comment] 2018-10-01 14:44
![image](https://user-images.githubusercontent.com/9441546/46295691-45824b80-c5cb-11e8-82f0-858a94b4db76.png)
![image](https://user-images.githubusercontent.com/9441546/46295724-5a5edf00-c5cb-11e8-8f9c-8d00850dae55.png)
why we need another button?
can't this backup whold settings?

**Comment by mallowigi** [comment] 2018-10-01 14:54
He probably meant export as an xml file rather than going into the config folder

**Comment by arnesacnussem** [comment] 2018-10-01 15:19
> He probably meant export as an xml file rather than going into the config folder

he says want to share,so another "import" button is in need

since IDEA born whit a Im/Ex-port function,why do you want to build wheels again??

**Comment by mallowigi** [comment] 2018-10-01 16:03
I read it like the import/export button in the color schemes, something like import/export custom themes rather than the whole export settings

**Comment by TomKriek** [comment] 2018-11-05 14:40
There absolutely needs to be a dedicated export functionality for the material theme. Every single time I need to transfer over my settings for PhpStorm it all breaks when transferring settings from this plugin. It's such a hassle to even get over half of the configuration that I just end up manually configuring again each time. The export together with the export of PhpStorm simply does not what it's supposed to be doing. Syncing via a JetBrains account also completely breaks all kinds of settings for the Material Theme. Please up the priority of this issue.

**Comment by mallowigi** [comment] 2018-11-28 07:07
After much consideration I will not do an export function since the IDE's Export Settings is working as intended.

**Closed by mallowigi** 2018-11-28 07:07 UTC
Labels: feature-request
