### ISSUE TITLE
Android Studio project view does not load after update

### ISSUE THREAD

**Issue by jahirfiquitiva** [ChrisRM/material-theme-jetbrains#568] opened 2018-01-06 19:30 UTC
**Without Plugin enabled**
![screenshot_2](https://user-images.githubusercontent.com/10360816/34643178-c7e7aa18-f2ed-11e7-9619-3c7ac77898c9.png)

**With Plugin enabled**
![screenshot_3](https://user-images.githubusercontent.com/10360816/34643208-5488d8de-f2ee-11e7-8c00-b93a687c6780.png)

When I enable the plugin, the project view does not load at all. It just show that little spinner in the top right corner.

### Environment

Android Studio 3.0.1 Stable
Windows 10
Plugin version: 1.5.3

**Comment by GeeksEmpireNet** [comment] 2018-01-06 23:41
Same here.
It throws NoSuchMethodError
`java.lang.NoSuchMethodError: com.intellij.ide.projectView.impl.ProjectRootsUtil.findUnloadedModuleByContentRoot(Lcom/intellij/openapi/vfs/VirtualFile;Lcom/intellij/openapi/project/Project;)Ljava/lang/String;`

**Comment by yunussandikci** [comment] 2018-01-07 01:20
same here

**Comment by mallowigi** [comment] 2018-01-07 08:24
duplicate of #571

**Closed by mallowigi** 2018-01-07 08:24 UTC
