### ISSUE TITLE
Error when starting WebStorm 2017.1

### ISSUE THREAD

**Issue by mrenty** [ChrisRM/material-theme-jetbrains#315] opened 2017-03-21 07:36 UTC
After updating to WebStorm 2017.1 (WS-171.3780.79) I got this error `com.intellij.ui.tabs.impl.DefaultEditorTabsPainter: method <init>()V not found`.

**Comment by vadim-kovalenko** [comment] 2017-03-21 07:59
Same problema

**Comment by jbouhier** [comment] 2017-03-21 15:05
Duplicate of https://github.com/ChrisRM/material-theme-jetbrains/issues/310

**Comment by denofevil** [comment] 2017-03-21 16:23
@jbouhier thank you, closing this on in favour of #310

**Closed by denofevil** 2017-03-21 16:23 UTC
