### ISSUE TITLE
Not visible edit icon

### ISSUE THREAD

**Issue by pronovaso** [ChrisRM/material-theme-jetbrains#1283] opened 2019-07-23 19:14 UTC
### Summary
I dont see edit icon in tab
...

### Expected behavior
When I editing the file,icon are showing
...

### Actual behavior
When I editing the file,icon dont showing
...

### Environment

It should contain:
* OS Mac OS 10.14.6
* Webstorm 2019.2
* Plugin version last

**Comment by taylorgoolsby** [comment] 2019-07-23 19:18
I think this is the ticket I'm looking for. To give more detail, the problem is that the modified icon does not exist.
![image](https://user-images.githubusercontent.com/14286600/61740515-a9852480-ad43-11e9-8ba9-5e0d98e6a717.png)
![image](https://user-images.githubusercontent.com/14286600/61740556-c3bf0280-ad43-11e9-8038-bd085b687d92.png)

**Comment by taylorgoolsby** [comment] 2019-07-23 19:20
Until it's fixed, you can disable icons in material theme:
![image](https://user-images.githubusercontent.com/14286600/61740735-37610f80-ad44-11e9-8d07-7e97683955be.png)

**Comment by pronovaso** [comment] 2019-07-23 19:22
> Until it's fixed, you can disable icons in material theme:
> ![image](https://user-images.githubusercontent.com/14286600/61740735-37610f80-ad44-11e9-8d07-7e97683955be.png)

You are right.This help me. Can I change the color of these icon in Material Theme or not?

**Comment by leafoflegend** [comment] 2019-07-23 20:26
+1 Please resolve 🙏

**Comment by mallowigi** [comment] 2019-07-26 12:55
fixed in 4.2

**Closed by mallowigi** 2019-07-26 12:55 UTC
