### ISSUE TITLE
Native themes are broken again

### ISSUE THREAD

**Issue by roni-estein** [ChrisRM/material-theme-jetbrains#1063] opened 2018-11-29 06:41 UTC
<img width="1920" alt="screen shot 2018-11-29 at 12 44 48 am" src="https://user-images.githubusercontent.com/8517475/49204016-0aed2300-f370-11e8-800b-9735e909cf85.png">
### Summary

Just upgraded phpstorm on autopilot, I should know better but actually this has been very smooth for the last 2 years at least. Material theme now is pretty jarring with the exterior of the screen when in any of the darker modes. All the screen items are stuck in the light mode.

### Expected behavior

Material dark based themes all have dark status bars and borders

### Actual behavior

All the bars annd borders are light regardless of the chosen theme.

### Steps to reproduce (if needed)

1. Install or update to PhpStorm 2018.3
Build #PS-183.4284.150, built on November 21, 2018
Licensed to Roni Estein
Subscription is active until September 29, 2019
JRE: 1.8.0_152-release-1343-b15 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.1

2. Install Material Theme UI

3. Select material Dark
And you get a jarring light surround
https://github.com/roni-estein/github-screenshots/blob/master/Screen%20Shot%202018-11-29%20at%2012.35.52%20AM.png
<img width="1920" alt="screen shot 2018-11-29 at 12 35 52 am" src="https://user-images.githubusercontent.com/8517475/49203850-5f43d300-f36f-11e8-99b3-6e53079941b9.png">

Previously Dark Backgrounds have also been infiltrated.

**Comment by mallowigi** [comment] 2018-11-29 10:35
Can't reproduce. Can you share your parameters and also your plugin list? 

Which version of the plugin do you have?

**Comment by roni-estein** [comment] 2018-11-30 00:09
Sure, can you give me a bit of direction, I use phpstorm 2018.3, just updates when it rolled out and I've been using the material theme plugin for at least 18 months, without much configuration except for the font, I prefer operator mono 10px with 1.4 line height.

Would you like a list of installed plug-ins or is there a file I can post for you?

Is there a way for a complete removeal and re-installation?

**Comment by mallowigi** [comment] 2018-11-30 12:09
Just provide me a screenshot of the list of installed plugins

**Comment by mallowigi** [comment] 2018-11-30 12:14
Perhaps you can try restarting your configuration to defaults by pressing the reset defaults button on the Material Theme settings screen

**Comment by ViralLka** [comment] 2018-11-30 12:58
I have the same problems. Phpstorm 2018.3

**Comment by roni-estein** [comment] 2018-11-30 18:40
No, I did the following, I'm on MacOS, so these instructions wont be identical for everyone.

Steps:

1. I Uninstalled all my theme based plugins. There was really only material theme ui and I had rainglow themes installed. Now, I've had the same setup for years, it's never been a problem until my update to 2018.3.

This had no effect.

2. I closed phpstorm and deleted all my ~/Library/Cache for phpstorm all versions. I had many versions.

3. I removed all the offending plugins from the plugins directory in php storm 
~/Library/Application Support/phpstorem

4. I deleted everything for all ~/Library/Preferences/phpstorm all versions except for 2018.3.
I renamed that to old-2018.3 which forced phpstorm to make a new version where everything worked.

5. I then tried copying a few files over but it created the same problem so I deleted it and moved over a few of my options, my macros and my keyboard shortcuts.


When I have a couple of hours to chase down the exact preference file I will, I believe it's in the options directory. And it's probably a benign setting that became active with the new phpstorm updates.

**Comment by Inkromind** [comment] 2018-12-03 10:16
I just had the same problem in IntelliJ after updating it to 2018.3 and the plugin to 3.0.0-something
Reverting the plugin to 2.10.6 fixed it (download the zip of the old version and then use "install plugin from disk" to install it).
It seems the 3.0.0-version is not yet ready. Unfortunately, it's the version that gets used when updating the plugin...

**Comment by mallowigi** [comment] 2018-12-03 18:01
Ok for those concerned, please go to the slack channel and contact me so i can pinpoint the exact source. For now there seems not to be reproducible easily so I'm closing this issue.

**Closed** 2018-12-18 15:46 UTC
