### ISSUE TITLE
com.intellij.ui.tabs.impl.DefaultEditorTabsPainter: method <init>()V not found

### ISSUE THREAD

**Issue by ktomi42** [ChrisRM/material-theme-jetbrains#316] opened 2017-03-21 12:17 UTC
com.intellij.ui.tabs.impl.DefaultEditorTabsPainter: method <init>()V not found
java.lang.NoSuchMethodError: com.intellij.ui.tabs.impl.DefaultEditorTabsPainter: method <init>()V not found
	at com.chrisrm.idea.MTTabsPainterPatcher$MTTabsPainter.<init>(MTTabsPainterPatcher.java:106)
	at com.chrisrm.idea.MTTabsPainterPatcher.patchPainter(MTTabsPainterPatcher.java:73)
	at com.chrisrm.idea.MTTabsPainterPatcher.access$000(MTTabsPainterPatcher.java:29)
	at com.chrisrm.idea.MTTabsPainterPatcher$1.selectionChanged(MTTabsPainterPatcher.java:57)
	at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:437)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:398)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:387)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:380)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:373)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:44)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:230)
	at com.sun.proxy.$Proxy81.selectionChanged(Unknown Source)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.a(FileEditorManagerImpl.java:1548)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$5$1.run(FileEditorManagerImpl.java:1031)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.b(FocusManagerImpl.java:655)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.h(FocusManagerImpl.java:639)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.p(FocusManagerImpl.java:609)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.access$200(FocusManagerImpl.java:61)
	at com.intellij.openapi.wm.impl.FocusManagerImpl$IdleRunnable.runEdt(FocusManagerImpl.java:107)
	at com.intellij.openapi.util.EdtRunnable.lambda$run$0(EdtRunnable.java:27)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2621)
	at com.intellij.openapi.util.EdtRunnable.run(EdtRunnable.java:25)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by jbouhier** [comment] 2017-03-21 15:05
Duplicate of https://github.com/ChrisRM/material-theme-jetbrains/issues/310

**Comment by denofevil** [comment] 2017-03-21 16:24
@jbouhier thank you, closing this on in favour of #310

**Closed by denofevil** 2017-03-21 16:24 UTC
