### ISSUE TITLE
Material Theme causing IntelliJ IDEA to freeze up completely.

### ISSUE THREAD

**Issue by samantharachelb** [ChrisRM/material-theme-jetbrains#1528] opened 2020-02-24 20:40 UTC
### Summary
The Material Theme UI plugin has made the IntelliJ IDEA IDE completely unusable. It freezes when you try to create files, delete files, edit files, or do anything with the IDE.

### Expected behavior
The program should not freeze.

### Actual behavior
The program freezes on start-up.  After the Material Theme UI plugin is disabled, the IDE no longer freezes.

### Steps to reproduce (if needed)

1. Open the IDE on your machine
2. Either open a project, or let the program automatically re-open the last project that was open.
3. The program does one of four things:
    * Freezes immediately after starting and opening a project.
    * Freezes when you try to create a file. The file ends up being created, but the UI is stuck displaying the "Create File" dialogue.
    * Freezes when you try to edit a file.
    * Freezes when you try to delete a file. Behaviour is exactly like the freeze on creating file.

### Environment
OS: macOS Catalina 10.15.3
Affected Plugin Versions:
- Material Theme UI Lite: v8.0
- Material Theme UI: v4.11.5

Tested with:
IntelliJ Product: IDEA (Ultimate Edition) 2019.3.3 (Build #: IU-193.6494.35, built Feb. 10, 2020)
Runtime Version: 1.8.0_231-b11 x86_64
VM: Java HotSpot™ 64-Bit Server VM by Oracle Corporation

IntelliJ Product: IDEA (Ultimate Edition) 2019.3.3 (Build #: IU-193.6494.35, built Feb. 10, 2020)
Runtime version: 11.0.5+10-b520.38 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

VM Options:
```
-Xms1024m
-Xmx4096m
-XX:ReservedCodeCacheSize=240m
-XX:+UseConcMarkSweepGC
-XX:SoftRefLRUPolicyMSPerMB=50
-ea
-XX:CICompilerCount=2
-Dsun.io.useCanonPrefixCache=false
-Djava.net.preferIPv4Stack=true
-Djdk.http.auth.tunneling.disabledSchemes=""
-XX:+HeapDumpOnOutOfMemoryError
-XX:-OmitStackTraceInFastThrow
-Djdk.attach.allowAttachSelf=true
-Dkotlinx.coroutines.debug=off
-Djdk.module.illegalAccess.silent=true
-XX:+UseCompressedOops
-Dfile.encoding=UTF-8
-XX:ErrorFile=$USER_HOME/java_error_in_idea_%p.log
-XX:HeapDumpPath=$USER_HOME/java_error_in_idea.hprof
-Dide.no.platform.update=true
```

Other Enabled Plugins:
| Plugin Name | Version  |
| :------------ | :-------- |
| .ignore          | 3.2.3.193 |
| Choose Runtime | 1.0.8 |
| License Generator | 0.0.7 |

I went through a process of elimination and have already determined that none of the above plugins is causing the issue. The issue is confirmed to be with the Material Theme UI plugin and only occurs when using it in conjunction with IntelliJ IDEA, and may be related to the bug reported in #855 

Please note that this issue **does not** happen with any of the other IDEs including CLion, PyCharm, PhpStorm, or WebStorm

I've attached both a thread dump and the material_theme.xml
[material_theme.xml.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/4246744/material_theme.xml.zip)
[threadDump-20200224-151411.txt](https://github.com/ChrisRM/material-theme-jetbrains/files/4246748/threadDump-20200224-151411.txt)

**Comment by mallowigi** [comment] 2020-02-24 21:40
This bug is almost two years old, it isn't related at all. Also, it is highly unlikely that the lite version would be causing the issue, since it's only a bunch of json files. Can you at least re-enable it and see if that happens again?

I have been using my own plugin every day and didn't notice freezes, and I'm using it in conjunction with multiple other plugins. So I'm confused on how to tackle your issue. 

One other possibility: if you use Toolbox, perhaps you can try using a fresh configuration and see if the issue reproduces.

**Comment by samantharachelb** [comment] 2020-02-25 23:02
I tried re-enabling the lite version of the plugin and saw the issue again. Same thing happened when I re-enabled the full version of the plugin. The next thing I tried installing a fresh copy of IDEA Ultimate on a different Mac with similar specs using both Toolbox and the .dmg "drag and drop" with only the Material Theme UI plugin installed and still encountered the same issue. I was, however, able to get it to work without issue on a different machine running Ubuntu 18.04.

For some reason that I can't figure out, I only have this problem when using the plugin with IDEA Ultimate on macOS. I've had no issue running this plugin along with other plugins on any of the other IntelliJ programs.

**Comment by YourMCGeek** [comment] 2020-03-16 23:46
Hello friends,

I have just saw this issue and have experienced the same thing on both the Toolbox version and a fresh copy of IDEA Ultimate. I'm running on a Windows 10 Home machine, and can provide full specs if you require it. Below is my IntelliJ specs. I was using Material Theme UI version 4.11.5 when I experienced this, both with Toolbox and with the standalone. The Material Theme that I was using was "Material Darker". It was the one straight out of the box as I didn't have a chance to edit it yet. 

```
IntelliJ IDEA 2019.3.3 (Ultimate Edition)
Build #IU-193.6494.35, built on February 10, 2020
Runtime version: 11.0.5+10-b520.38 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 725M
Cores: 6
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: CMD Support, com.almightyalpaca.intellij.plugins.discord, com.demonwav.minecraft-dev, mobi.hsz.idea.gitignore, org.jetbrains.kotlin
```
VM Options
```
-Xms128m
-Xmx750m
-XX:ReservedCodeCacheSize=240m
-XX:+UseConcMarkSweepGC
-XX:SoftRefLRUPolicyMSPerMB=50
-ea
-XX:CICompilerCount=2
-Dsun.io.useCanonPrefixCache=false
-Djava.net.preferIPv4Stack=true
-Djdk.http.auth.tunneling.disabledSchemes=""
-XX:+HeapDumpOnOutOfMemoryError
-XX:-OmitStackTraceInFastThrow
-Djdk.attach.allowAttachSelf=true
-Dkotlinx.coroutines.debug=off
-Djdk.module.illegalAccess.silent=true
-Dide.no.platform.update=true
```

It's happened numerous times, and therefore there are numerous thread dumps from the standalone IntelliJ. I've put it all into one rar file, which you can view below. Feel free to look at how ever many thread dumps you'd like. 

If you'd like any more information please let me know, I'm hoping to get this resolved as the dracula theme is quite frankly rather ugly compared to Material Theme. 

[threaddumps.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/4340818/threaddumps.zip)

**Comment by YourMCGeek** [comment] 2020-03-20 12:33
Looks like it's happening on 2019.3.4 for me also.

**Comment by mallowigi** [comment] 2020-04-09 08:46
Hi guys,

Is it still happening for 2020.1 ? I would want to close this.

**Closed** 2020-04-09 09:53 UTC
Labels: cannot reproduce
