### ISSUE TITLE
Tool windows getting duplicated

### ISSUE THREAD

**Issue by Danielhsc** [ChrisRM/material-theme-jetbrains#1815] opened 2021-08-05 14:58 UTC
### Summary

All tools windows are being duplicated and it is impossible to hide it. And every time we click on it, a new tool window is added.

### Expected behavior

When clicked, tools windows should not be duplicated

### Actual behavior

Every time we click on it, a new tool window is added.

### Steps to reproduce (if needed)

With this setting on (https://www.material-theme.com/docs/configuration/features-settings/#striped-tool-windows-layout)
![image](https://user-images.githubusercontent.com/5084883/128371696-dfba2ca8-77c8-4e5a-bd20-1654b38de4f0.png)

With setting off
![image](https://user-images.githubusercontent.com/5084883/128371771-12fd4360-94fb-4d41-881f-31129a15762c.png)

### Environment

2 open projects
Plugin version 6.8.0.1
PhpStorm 2021.2
Build #PS-212.4746.100, built on July 28, 2021
Runtime version: 11.0.11+9-b1504.13 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.8.0-63-generic

I don't know if it makes a difference, but this is my current tools windows layout:
On left side: Database, Laravel Tinker, NPM
On Right side: Project, Commit, 
On Right bottom side: Structure
On Bottom: Git, TODO, Problems, Terminal

**Comment by mallowigi** [comment] 2021-08-05 15:20
I will try to reproduce, but a few questions:
- Does it happen after you do a specific thing? Or does it happen from the start?
- Are you working fullscreen/zen mode

I must say that I've been working with this mode non-stop for 4 months and since I fixed the issue it didn't reproduce.

**Comment by Danielhsc** [comment] 2021-08-05 16:43
The first time it happened was right after the update to the new version of PHPStorm. And it only happens with the specified configuration turned on.
I also tested it on two different devices (Windows 10 and Mac M1 with OSX Big Sur 11.5.1) with the same version of PHP Storm and plugin. The behavior was the same.
I don't use zen mode or fullscreen mode. Just the good old maximized screen.

Tonight I will do some new tests with a clean install of PHPStorm and plugins and see if the behavior will be the same.

**Comment by mallowigi** [comment] 2021-08-13 18:50
Closing issues regarding the Stripe Tool windows as it will be handled by JB's side (approx. ETA: 2022.1)

**Closed by mallowigi** 2021-08-13 18:50 UTC
