### ISSUE TITLE
Pulling out the card with an open file from the main window causes Webstorm crash

### ISSUE THREAD

**Issue by hstaniszewski** [ChrisRM/material-theme-jetbrains#855] opened 2018-07-25 14:23 UTC
### Summary
Pulling out the card with an open file from the main window (I work on two monitors) results in the program being suspended.

### Expected behavior.
The program should not freeze

### Actual behavior

The program freezes. After disabling the Material Theme UI plugin, this action does not freeze the program.

### Steps to reproduce (if needed)

1. Open some file in the active project
2. Catch the card with the file and pull it out of the program (for example, on the second screen)
3. The program is crashing 

### Environment

WebStorm 2018.2
Build #WS-182.3684.70, built on July 20, 2018
JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.3

**Comment by mallowigi** [comment] 2018-07-26 07:53
What is a card

**Comment by hstaniszewski** [comment] 2018-07-26 07:59
Opened files:

![image](https://user-images.githubusercontent.com/19909276/43249239-7d4789ea-90ba-11e8-8346-63415d7292d8.png)

**Comment by mrkirby153** [comment] 2018-07-26 21:59
I am able to reproduce this bug using IntelliJ Ultimate 2018.2 so it isn't limited to only EAP builds. After pulling a file into a new window, the app freezes and crashes.

### Environment
IntelliJ IDEA 2018.2 (Ultimate Edition)
Build #IU-182.3684.101, built on July 24, 2018
JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

**Comment by mallowigi** [comment] 2018-07-27 11:17
OMG my whole computer got unresponsive!!! What the heck did they do in the last release????

**Comment by mallowigi** [comment] 2018-07-27 11:19
I'm also using this feature a lot, almost every day and it never froze. But I'm on windows, it could be the reason. On Mac it is completely broken.

**Comment by mallowigi** [comment] 2018-07-27 16:10
I think i found the reason. Please update to 2.7.0 it should be fixed.

**Closed by mallowigi** 2018-07-27 16:10 UTC
Labels: Critical, EAP

**Comment by hstaniszewski** [comment] 2018-07-27 16:50
It's working fine now. Thank you!

**Comment by bsavio** [comment] 2018-07-31 14:33
I'm getting a similar issue.  The difference is the PyCharm consistently hangs when I go to open settings.  Once I remove the plugin it works again.  Note, it also occurred after upgrading to 2.7

PY-182.3684.100, JRE 1.8.0_152-release-1248-b8x64 JetBrains s.r.o, OS Windows 7(amd64) v6.1 Service Pack 1
