### ISSUE TITLE
startup popup comes up every time

### ISSUE THREAD

**Issue by amirhosseindz** [ChrisRM/material-theme-jetbrains#939] opened 2018-09-19 16:57 UTC
### Summary

Startup configuration popup window opens on every time IDE launches, even I go through all steps and press the finish button.

### Expected behavior

Doesn't show startup configuration popup after first time.

### Actual behavior

Shows startup popup every time when I open the IDE.

### Environment

OS : Ubuntu 18.04.1 LTS
Material theme Version(it wasn't on the IDE about window) : 2.9.0-pre1

Copied from about window :
IntelliJ IDEA 2018.2.4 (Ultimate Edition)
Build #IU-182.4505.22, built on September 18, 2018
Licensed to IntelliJ IDEA Evaluator
Expiration date: October 19, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-34-generic

**Comment by mallowigi** [comment] 2018-09-19 18:17
Duplicate of #936

**Closed by mallowigi** 2018-09-19 18:17 UTC
