### ISSUE TITLE
Null color descriptor in MTFileColorsPage.getColorDescriptors()

### ISSUE THREAD

**Issue by gregsh** [ChrisRM/material-theme-jetbrains#469] opened 2017-10-17 08:55 UTC
Exception here, seems due to threading issues.

Material Theme UI EAP (1.0.1)
```
2017-10-15 17:28:37,037 [  38396]  ERROR - ons.colors.ColorAndFontOptions - Assertion failed: com.chrisrm.idea.config.MTFileColorsPage 
java.lang.Throwable: Assertion failed: com.chrisrm.idea.config.MTFileColorsPage
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:172)
	at com.intellij.application.options.colors.ColorAndFontOptions.a(ColorAndFontOptions.java:623)
	at com.intellij.application.options.colors.ColorAndFontOptions.a(ColorAndFontOptions.java:596)
	at com.intellij.application.options.colors.ColorAndFontOptions.a(ColorAndFontOptions.java:586)
	at com.intellij.application.options.colors.ColorAndFontOptions.e(ColorAndFontOptions.java:576)
	at com.intellij.application.options.colors.ColorAndFontOptions.buildConfigurables(ColorAndFontOptions.java:440)
	at com.intellij.openapi.options.SearchableConfigurable$Parent$Abstract.getConfigurables(SearchableConfigurable.java:87)
	at com.intellij.openapi.options.ex.ConfigurableWrapper$CompositeWrapper.getConfigurables(ConfigurableWrapper.java:253)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.a(ShowSettingsUtilImpl.java:89)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.a(ShowSettingsUtilImpl.java:89)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.getConfigurables(ShowSettingsUtilImpl.java:80)
	at com.intellij.ide.util.gotoByName.GotoActionModel.a(GotoActionModel.java:87)
	at com.intellij.openapi.util.VolatileNotNullLazyValue$1.compute(VolatileNotNullLazyValue.java:54)
	at com.intellij.openapi.util.VolatileNotNullLazyValue.getValue(VolatileNotNullLazyValue.java:34)
	at com.intellij.ide.util.gotoByName.GotoActionModel.getConfigurablesNames(GotoActionModel.java:315)
	at com.intellij.ide.util.gotoByName.GotoActionItemProvider.e(GotoActionItemProvider.java:129)
	at com.intellij.ide.util.gotoByName.GotoActionItemProvider.filterElements(GotoActionItemProvider.java:89)
	at com.intellij.ide.util.gotoByName.GotoActionItemProvider.filterElements(GotoActionItemProvider.java:73)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.a(ChooseByNameBase.java:1439)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.a(ChooseByNameBase.java:1415)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.a(ChooseByNameBase.java:1397)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.performInReadAction(ChooseByNameBase.java:1362)
	at com.intellij.openapi.progress.util.ReadTask.a(ReadTask.java:66)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.runBackgroundProcess(ChooseByNameBase.java:1349)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:238)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:534)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:479)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:236)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:47)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mallowigi** [comment] 2017-10-19 06:03
Cannot reproduce. Is it happening frequently? Because I don't have any issues with it.

**Comment by roboslone** [comment] 2017-10-19 10:41
It seems that issue only occurs with high-DPI screens. It's happening all the time.

**Comment by roboslone** [comment] 2017-10-19 21:43
It seems issue is gone in the latest EAP.

PyCharm 2017.3 EAP (Professional Edition)
Build #PY-173.3302.15, built on October 19, 2017
PyCharm EAP User
Expiration date: November 18, 2017
JRE: 1.8.0_152-release-1024-b5 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

**Comment by mallowigi** [comment] 2017-10-21 21:15
can we close it then?

**Comment by roboslone** [comment] 2017-10-22 13:36
Sure.

**Comment by gregsh** [comment] 2017-10-22 18:49
@mallowigi I changed LOG.error to LOG.warn in order not to crash everything.
See https://github.com/JetBrains/intellij-community/commit/de6168bc13bba351fa0011f5a40fe2b1a31fb41f#diff-ed93e93081b7541d59efe995cf181f9c

So I'd watch logs for that anyway. The code in MTFileColorsPage is not thread safe, 
while it is invoked from many threads. At least the field shall be assigned *after* it is populated.

**Comment by mallowigi** [comment] 2017-10-22 20:27
This is what I’m trying to do: assign a color to the color scheme for each fileStatus color. It works well but somehow you get this error.

I’m not an expert in Java, so all threadsafe development is hard to me, but you’re welcome to help fix it :)

--
Elior

**Closed** 2017-10-29 08:24 UTC
