### ISSUE TITLE
File colors works only for the active tab

### ISSUE THREAD

**Issue by krouxe** [ChrisRM/material-theme-jetbrains#1341] opened 2019-08-23 07:27 UTC
### Summary

File colors is broken again. Now only the active tab is colored.

### Expected behavior
All tabs should be colored given File Colors configuration 

### Actual behavior
The active tab is colored. Others are not.

**Comment by annechko** [comment] 2019-08-30 12:16
+1, observing the same error

**Comment by mallowigi** [comment] 2019-08-30 13:37
Duplicate of an already opened bug, please check before opening issues

**Closed by mallowigi** 2019-08-30 13:37 UTC
